### PR TITLE
Store brightness if set.

### PR DESCRIPTION
**Pull request by aequitas**
This is part one of a fix to make HA show the correct brightness setting.

### CODE REVIEW

**Comment by Danielhiversen** [comment]
Here https://github.com/Danielhiversen/flux_led/pull/25/files#diff-432c4d3e79417f8676dc71ae5e419702R625 you should add:

```
if self.mode == "ww":
   self._brightness = int(self.raw_state[9])
```


And change getWarmWhite255() to always return self._brightness .
Then you do not have to change anything in HA?

**Comment by aequitas** [comment]
Correct, the WW/CW level should be returned as brightness in it is an rgbw. But I think returning the rgb brightness in getWarmWhite255 is expanding that method to where it is not intended for. 

I have some more changes upcoming for this device in HA so doesn't hurt to have one more :)

**Comment by Danielhiversen** [comment]
>> But I think returning the rgb brightness in getWarmWhite255 is expanding that method to where it is not intended for.

Agree to that.
So change the HA code to always use brightness (and not getWarmWhite255) should work?

**Comment by aequitas** [comment]
Also I think your suggested change will not work in that place, as the state of the bulb has not been updated afaics, so raw_state still has the old value.

I also think getting the rgb brightness level from reverse calculating the rgb would maybe be a better solution as it will not result in falsely reporting brightness if it is changed externally (via the RF remote or another client). I will try to make some updates later today.

**Comment by aequitas** [comment]
I removed some unused private variables. `brightness` property now returns WW level or RGB brightness equivalent (RGB->HSV->V) depending on mode. Kept `getWarmWhite255` for backwards compatibility.

**Comment by Danielhiversen** [comment]
Great. Thanks.
The code looks fine, but I will not be able to test it before next week.
@tchellomello Are you able to test this?

**Comment by aequitas** [comment]
No problem. Thanks for the invitation. Do you have any particular direction you want to head to with this repository or keep it as is and change only where needed? There seems to be some legacy from the original author so while i'm touching code I might refactor it some bit.

**Comment by Danielhiversen** [comment]
I do not have much time to work on this repo, so it would be great if you want to do some refactorization.
The code would benefit of some clean ups. It would also be great to have some flake8/pylint test and some auto tests.

**Comment by Danielhiversen** [comment]
Did quick test, and it seams to be fine.

**Pull request merged**
